### ISSUE TITLE
Prune the integration database

### ISSUE THREAD

**Issue by jimwebber** [neo-technology-field/sync-extension#3]
The integration database cannot grow indefinitely.

Must figure out a safe way of pruning it. 

Must figure out a good trigger for starting the pruning activity:

* Could be manual, launched via procedure
* Probably should be automated
* Unsure whether it should be part of the regular build up of integration database state

**Comment by cupkes** [comment]
So, I basically call a pruning query every time we run a pull query.  I'm going to say that this feature is complete for this coming release.
