### ISSUE TITLE
Bulk loading

### ISSUE THREAD

**Issue by jimwebber** [neo-technology-field/sync-extension#9]
Need to be tolerant of bulk loading.

Either have a bulk load mode (customer doesn't like that because ops)
Or

When pulling data across the wire, don't pull from last to current, but from last to last + offset (e.g. 1000) or current whichever is smallest. This means the same code path for bulk and non-bulk which is nicer.

**Comment by cupkes** [comment]
I think we're just going to roll with the limit clause in the polling query.  We'll configure the batch size in the neo4j.conf file.
